# Generated by Django 6.0.4 on 2026-04-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('aiml_intern', 'AI/ML Intern'), ('bde_intern', 'Business Development Intern'), ('dev_intern', 'Software Development Intern'), ('design_intern', 'UI/UX Design Intern'), ('marketing_intern', 'Digital Marketing Intern'), ('data_intern', 'Data Analyst Intern'), ('content_intern', 'Content Writing Intern'), ('hr_intern', 'HR Intern')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('duration', models.CharField(default='3 months', max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Why do you want this role?'),
        ),
        migrations.AddField(
            model_name='application',
            name='role_applied_for',
            field=models.CharField(choices=[('aiml_intern', 'AI/ML Intern'), ('bde_intern', 'Business Development Intern'), ('dev_intern', 'Software Development Intern'), ('design_intern', 'UI/UX Design Intern'), ('marketing_intern', 'Digital Marketing Intern'), ('data_intern', 'Data Analyst Intern'), ('content_intern', 'Content Writing Intern'), ('hr_intern', 'HR Intern')], default='dev_intern', help_text='Internship role the applicant is applying for', max_length=50),
        ),
    ]
