# Generated by Django 6.0.4 on 2026-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_internprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='current_round',
            field=models.IntegerField(default=1, help_text='Current active round (1-5)'),
        ),
    ]
