# Generated by Django 6.0.4 on 2026-05-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_alter_application_phone_alter_application_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
