# Generated by Django 5.2.15 on 2026-08-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_alter_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('employee', 'Full-Time Job')], default='internship', max_length=20),
        ),
        migrations.AddField(
            model_name='openposition',
            name='position_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('employee', 'Full-Time Job')], default='internship', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='role_applied_for',
            field=models.CharField(choices=[('aiml_intern', 'AI/ML Intern'), ('bde_intern', 'Business Development Intern'), ('dev_intern', 'Software Development Intern'), ('design_intern', 'UI/UX Design Intern'), ('marketing_intern', 'Digital Marketing Intern'), ('data_intern', 'Data Analyst Intern'), ('content_intern', 'Content Writing Intern'), ('hr_intern', 'HR Intern'), ('full_stack_dev', 'Full Stack Developer'), ('backend_dev', 'Backend Engineer'), ('frontend_dev', 'Frontend Developer'), ('ui_ux_designer', 'UI/UX Designer'), ('hr_manager', 'HR Executive / Manager'), ('marketing_manager', 'Growth & Marketing Lead')], default='dev_intern', help_text='Role the applicant is applying for', max_length=50),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='role',
            field=models.CharField(choices=[('aiml_intern', 'AI/ML Intern'), ('bde_intern', 'Business Development Intern'), ('dev_intern', 'Software Development Intern'), ('design_intern', 'UI/UX Design Intern'), ('marketing_intern', 'Digital Marketing Intern'), ('data_intern', 'Data Analyst Intern'), ('content_intern', 'Content Writing Intern'), ('hr_intern', 'HR Intern'), ('full_stack_dev', 'Full Stack Developer'), ('backend_dev', 'Backend Engineer'), ('frontend_dev', 'Frontend Developer'), ('ui_ux_designer', 'UI/UX Designer'), ('hr_manager', 'HR Executive / Manager'), ('marketing_manager', 'Growth & Marketing Lead')], max_length=50, unique=True),
        ),
    ]
