# Generated by Django 5.2.15 on 2026-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_application_app_type_openposition_position_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
