# Generated by Django 6.0.4 on 2026-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_intern_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='round_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
