# Generated by Django 6.0.4 on 2026-04-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('mentor', 'Mentor'), ('team_head', 'Team Head'), ('team_member', 'Team Member'), ('intern', 'Intern')], default='intern', max_length=20),
        ),
    ]
