# Generated by Django 6.0.4 on 2026-05-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_direct_enroll',
            field=models.BooleanField(default=False),
        ),
    ]
