# Generated by Django 5.2.15 on 2026-08-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mentor',
        ),
    ]
