# Generated by Django 5.2.15 on 2026-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mentor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
